#加密配置
jasypt:
  encryptor:
    password: fx

server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads

spring:
  redis:
    remote: false        #cachecloud 获取
    host: 192.168.1.167
    port: 6379
    password: 123456
  rabbitmq:
    host: 192.168.1.184
    port: 5672
    username: fx
    password: 123456
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

redis:
  cache:
    expiration: 3601

ribbon:
  eager-load:
    enabled: true  #饥饿模式，解决ribbon客户端在调用的时候第一次慢导致超时的问题（在首次调用才初始化）
    clients: auth-server,upms-service
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true  ##ribbon use okhttp instead of httpclient
  httpclient:
    enabled: false
  client:  #定制@FeignClient
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:  #开启压缩可以有效节约网络资源，但是会增加CPU压力
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#监控短点配置 在1.5.x版本中通过management.security.enabled=false来暴露所有端点
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

